name = "UniformWindows"
uuid = "0ee29da2-f160-48e8-9d45-f73035afdb83"
authors = ["kmsherbertvt <kyle.sherbert@vt.edu>"]
version = "0.1.0"

[deps]
CtrlVQE = "b0286c9f-ec41-4a06-9137-e6f7f9cecc08"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
